### ISSUE TITLE
Make milliseconds optional for dates

### ISSUE THREAD

**Issue by NickGrantONS** [ONSdigital/census-int-common-service#26]
The class `uk.gov.ons.ctp.common.event.model.Header` uses `@JsonFormat` with a pattern to marshal a string date in ISO format into a `java.util.Date` object.

There are two options for handling dates in a way which will handle ALL valid ISO formats:
- Use `OffsetDateTime` instead of `java.util.Date`.
- Specify the millisecond part inside square brackets to make it optional

The second option (pattern of `"yyyy-MM-dd'T'HH:mm:ss[.SSS]X"` inside class `uk.gov.ons.ctp.common.time.DateTimeUtil.DATE_FORMAT_IN_JSON`) would be a very minor code change, allowing RH to handle all valid ISO dates, with a very trivial code change.

**Comment by philwhiles** [comment]
Different approach was adopted
